{{- if .Values.api.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "django-app.fullname" . }}-api
  labels:
    app: {{ include "django-app.fullname" . }}
    component: api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django-app.fullname" . }}
      component: api
  template:
    metadata:
      annotations:
        {{- include "django-app.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "django-app.fullname" . }}
        component: api
        {{- with (include "django-app.appDefaultLabels" $) -}}{{ . | nindent 8 }}{{- end }}
    spec:
      {{- with (include "django-app.appDefaultVolumes" $) -}}{{ . | nindent 6 }}{{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "django-app.serviceAccountName" $ }}
      {{- end }}
      containers:
        - name: api
          {{- include "django-app.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.api.image)
              | nindent 10
          }}
          command:
            {{- toYaml .Values.api.command | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          # TODO: livenessProbe
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            {{- include "django-app.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "django-app.envTemplate"
              (dict "Values" $.Values "Type" "web" )
              | nindent 12
          }}

{{- end }}
