{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "django-app.fullname" . }}-api
  labels:
    app: {{ include "django-app.fullname" . }}
    component: api
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
    {{- with .Values.ingress.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ required "ingress.className" .Values.ingress.className | quote }}
  rules:
    - host: {{ required "ingress.host" .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "django-app.fullname" . }}-api
                port:
                  number: 80

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ required "ingress.tls.secretName" .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.host | quote }}
  {{- end }}

{{- end }}
