{{- if .Values.worker.enabled }}

{{- range $queue_name, $config := .Values.worker.queues }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "django-app.fullname" $ }}-worker-{{ $queue_name }}
  labels:
    app: {{ include "django-app.fullname" $ }}
    component: worker
    queue: {{ $queue_name }}
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "django-app.fullname" $ }}
      component: worker
      queue: {{ $queue_name }}
  template:
    metadata:
      annotations:
        {{- include "django-app.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "django-app.fullname" $ }}
        component: worker
        queue: {{ $queue_name }}
        {{- with (include "django-app.appDefaultLabels" $) -}}{{ . | nindent 8 }}{{- end }}
    spec:
      {{- with (include "django-app.appDefaultVolumes" $) -}}{{ . | nindent 6 }}{{- end }}
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "django-app.serviceAccountName" $ }}
      {{- end }}
      containers:
        - name: worker
          command:
            {{- toYaml $.Values.worker.queueCommandPrefix | nindent 12 }}
            {{- toYaml $config.celeryArgs | nindent 12 }}
          {{- include "django-app.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.worker.image)
              | nindent 10
          }}
          # TODO: livenessProbe
          resources:
            {{- include "django-app.resourcesConfig"
                (dict "Default" $.Values.worker.queueDefaultResources "Override" $config.resources)
                | nindent 12
            }}
          envFrom:
            {{- include "django-app.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "django-app.envTemplate"
                (dict "Values" $.Values "Type" "worker" )
                | nindent 12
            }}

{{- end }}

{{- end }}
