{{- if .Values.worker.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "django-app.fullname" . }}-worker-beat
  labels:
    app: {{ include "django-app.fullname" . }}
    component: worker-beat
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: 1  # This should only 1
  selector:
    matchLabels:
      app: {{ include "django-app.fullname" . }}
      component: worker-beat
  template:
    metadata:
      annotations:
        {{- include "django-app.appDefaultAnnotations" $ | nindent 8 }}
      labels:
        app: {{ include "django-app.fullname" . }}
        component: worker-beat
        {{- with (include "django-app.appDefaultLabels" $) -}}{{ . | nindent 8 }}{{- end }}
    spec:
      {{- with (include "django-app.appDefaultVolumes" $) -}}{{ . | nindent 6 }}{{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "django-app.serviceAccountName" $ }}
      {{- end }}
      containers:
        - name: worker-beat
          {{- include "django-app.imageConfig"
              (dict "Default" $.Values.image "Override" $.Values.worker.beat.image)
              | nindent 10
          }}
          command:
            {{- toYaml .Values.worker.beat.command | nindent 12 }}
          # TODO: livenessProbe
          resources:
            {{- toYaml .Values.worker.beat.resources | nindent 12 }}
          envFrom:
            {{- include "django-app.envFromTemplate" $ | nindent 12 }}
          env:
            {{- include "django-app.envTemplate"
                (dict "Values" $.Values "Type" "worker" )
                | nindent 12
            }}

{{- end }}
